<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/layout/head.phtml'; ?>
    <script defer src="js/adminPasscodeModal.js"></script>
    <script defer src="js/adminPage.js"></script>
    <script defer src="js/signOutByAdminModal.js"></script>
    <link href="css/adminPage.css" type="text/css" rel="stylesheet">
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>
<main class="admin_page">
    <div class="buttons-container">
        <a href="/logout"><button>LOG OUT</button></a>
        <button id="visitorsIn"> Visitors Currently In</button>
        <button id="visitorsOut"> Visitors History</button>
        <button id="allVisitors"> All Visitors</button>
        <button id="signOutAll" type="button" class="signOutButtonAdmin btn btn-secondary
                btn-lg active admin-btn" data-toggle="modal" data-target="#signOutAllModal  ">Sign Out All Visitors</button>
    </div>

    <div>
        <table>
        <tr>
            <th>NAME:</th>
            <th>COMPANY:</th>
            <th>DAY/TIME ENTERED:</th>
            <th>CURRENTLY IN/SIGN OUT TIME:</th>
            <?php echo \App\ViewHelpers\DisplayVisitorsViewHelper::displayVisitors($visitors); ?>
        </tr>
        </table>
    </div>
</main>
<!--modal-->
<div>
    <button class="hideElement" id="previous"> < </button>
    <button id="next"> > </button>
    <div class="modal fade" id="signOutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sign Out</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/signOutByAdmin">
                        <label for="hiddenInput"></label>
                        <input id="hiddenInput" type="hidden" value="" name="name">
                        <p>Are you sure you want to sign out for <span id="signOutName"></span>?</p>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="submitSignOut" type="submit" class="btn btn-primary">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!--modal sign Out ALl-->
    <div>
        <button class="hideElement" id="previous"> < </button>
        <button id="next"> > </button>
        <div class="modal fade" id="signOutAllModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Sign Out</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="/signOutAllByAdmin">
                            <input id="hiddenInputAll" type="hidden" value="" name="name">
                            <p>Are you sure you want to sign out All Visitors ?</p>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button id="submitSignOut" type="submit" class="btn btn-primary">Confirm</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>