<!DOCTYPE html>
<html lang="en">
    <head>
        <?php require 'partials/layout/head.phtml'; ?>
        <script defer src="js/signOutByAdminModal.js"></script>
        <script defer src="js/adminPasscodeModal.js"></script>
    </head>
    <body>
    <?php require 'partials/layout/header.phtml'; ?>
    <main class="admin_page">
        <div>
            <button><a href="/logout"> LOG OUT</a></button>
        </div>
        <div>
            <table>
            <tr>
                <th>NAME:</th>
                <th>COMPANY:</th>
                <th>DAY/TIME ENTERED:</th>
                <th>CURRENTLY IN:</th>
                <?php echo \App\ViewHelpers\DisplayVisitorsViewHelper::displayVisitors($visitors); ?>
            </tr>
            </table>
        </div>
    </main>
    <!-- Modal -->
    <div class="modal fade" id="signOutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sign Out</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/signOutByAdmin">
                        <label for="hiddenInput"></label>
                        <input id="hiddenInput" type="hidden" value="" name="name">
                        <p>Are you sure you want to sign out for <span id="signOutName"></span>?</p>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="submitSignOut" type="submit" class="btn btn-primary">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>