<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/layout/head.phtml'; ?>
</head>
<body>
    <?php require 'partials/layout/header.phtml'; ?>
    <div>Search for your name below to sign out</div>

    <form method="POST" action="/search">
    <div class="input-group">
        <input name="name" type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
               aria-describedby="search-addon" />
        <button type="submit" class="btn btn-outline-primary">search</button>
    </div>
    </form>

    <?php
    if (isset($visitors)) {
        echo '<table>' .
        '<tr>
            <th>NAME:</th>
            <th>COMPANY:</th>
            <th>DAY/TIME ENTERED:</th>' .
            \App\ViewHelpers\DisplayVisitorsViewHelper::displaySearchVisitors($visitors) .
    '</tr>
    </table>';
    };

    ?>
    <?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>
