<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/layout/head.phtml'; ?>
    <script defer src="js/signOutModal.js"></script>
</head>
<body>
    <?php require 'partials/layout/header.phtml'; ?>
    <div>Search for your name below to sign out</div>

    <form method="POST" action="/search">
    <div class="input-group">
        <input name="name" type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
               aria-describedby="search-addon" required/>
        <button type="submit" class="btn btn-outline-primary">search</button>
    </div>
    </form>
    <button class="btn btn-back" type="button" value="Back"><a href="/">Back</a></button>

    <?php
    if (isset($visitors)) {
        echo '<table>' .
        '<tr>
            <th>NAME:</th>
            <th>COMPANY:</th>
            <th>DAY/TIME ENTERED:</th>
            <th>SIGN OUT</th>' .
            \App\ViewHelpers\DisplayVisitorsViewHelper::displaySearchVisitors($visitors) .
    '</tr>
    </table>';
    };

    ?>
    <!-- Modal -->
    <div class="modal fade" id="signOutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sign Out</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/signOut">
                        <label for="hiddenInput"></label>
                        <input id="hiddenInput" type="hidden" value="" name="name">
                        <p>Are you sure you want to sign out for <span id="signOutName"></span>?</p>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="submitSignOut" type="submit" class="btn btn-primary">Confirm</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>
