<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'partials/layout/head.phtml'; ?>
    <link rel="stylesheet" href="css/homePage.css" type="text/css">


</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php if (isset($welcome)){echo '<p> Hello ' . $welcome . ', welcome to Bonjour!</p>';} ?>
<div class="options-header">
    <h1>Select Options</h1>
</div>
<div class="btn-container">
    <a class="btn btn-primary btn-lg" href="/newVisitor" role="button">Guest Login</a>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#adminModal">
        Admin Login
    </button>
<!--    <a class="btn btn-primary btn-lg" data-toggle="modal" href="/admin" role="button">Admin Login</a>-->
</div>


<!-- Modal -->
<div class="modal fade" id="adminModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="/password">
                    <label for="adminPasscode"></label>
                    <input type="password" name="adminPasscode" id="adminPasscode">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>



<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>