<!DOCTYPE html>
<html lang="en">
    <head>
        <?php require 'partials/layout/head.phtml'; ?>
        <link href="/css/addVisitor.css" rel='stylesheet' type="text/css">
    </head>
    <body>
        <?php require 'partials/layout/header.phtml'; ?>
        <div class="title">
            <h1>Visitor Form</h1>
        </div>
        <div class="form-container">
            <form method="post" action="/newVisitor">
                <label for="name" >Name</label>
                <input id="name" name="name" type="text">
                <?php if (isset($error)){echo '<p class="error-msg">'.$error.'</p>';} ?>
                <label for="company" >Company <span>(Optional)</span></label>
                <input id="company" name="company" type="text">
                <div class="btn-container">
                    <a  class="btn btn-back" href="/"type="button" value="Back">Back</a>
                    <button class="btn btn-submit" type="submit" value="Submit">Submit</button>
                </div>
            </form>
        </div>
        <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>